name: Build and Release

on: push
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Package
        run: |
          docker build -t nbis-builder .
          mkdir dist
          docker run --rm -v $(pwd)/dist:/dist nbis-builder bash -c "cd /build && zip -r /dist/nbis-linux-amd64.zip *"

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_type == 'tag' && github.ref || github.head_ref }}
          draft: false
          prerelease: false

      - name: Upload Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/nbis-linux-amd64.zip
          asset_name: nbis-linux-amd64.zip
          asset_content_type: application/zip
