name: Build and Release

permissions:
  packages: write
  contents: write

on:
  push:
    tags: '*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Package
        run: |
          docker build -t nbis-builder .
          mkdir dist
          docker run --rm -v $(pwd)/dist:/dist nbis-builder bash -c "cd /build && tar -zcvf /dist/nbis-linux-amd64.tar.gz ."

      - name: Create Release
        uses: bruceadams/get-release@v1.3.2
        id: get_release
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./dist/nbis-linux-amd64.tar.gz
          asset_name: nbis-linux-amd64.tar.gz
          asset_content_type: application/gzip
